<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CL5VKH3" failures="1" tests="1" name="Default test" time="28.172" errors="0" timestamp="09 Apr 2021 12:50:27 GMT">
  <testcase classname="jl.project.Pa11yTest.UserRequirement5_Pa11yTest" name="@AfterClass release" time="0.348">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.lang.Process.supportsNormalTermination()&amp;quot; because &amp;quot;this.this$0.process_angular&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.Process.supportsNormalTermination()" because "this.this$0.process_angular" is nullat jl.project.Pa11yTest.UserRequirement5_Pa11yTest$2.call(UserRequirement5_Pa11yTest.java:230)at jl.project.Pa11yTest.UserRequirement5_Pa11yTest$2.call(UserRequirement5_Pa11yTest.java:1)at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:203)at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:190)at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)at java.base/java.lang.Thread.run(Thread.java:832)]]>
    </failure>
  </testcase> <!-- @AfterClass release -->
  <testcase classname="jl.project.Pa11yTest.UserRequirement5_Pa11yTest" name="pa11yTest" time="0.013">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionErrorat org.junit.Assert.fail(Assert.java:87)at org.junit.Assert.assertTrue(Assert.java:42)at org.junit.Assert.assertTrue(Assert.java:53)at jl.project.Pa11yTest.UserRequirement5_Pa11yTest.pa11yTest(UserRequirement5_Pa11yTest.java:209)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- pa11yTest -->
</testsuite> <!-- Default test -->
